// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: api/api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TgBot_TaskAdd_FullMethodName = "/api.TgBot/TaskAdd"
	TgBot_Ping_FullMethodName    = "/api.TgBot/Ping"
)

// TgBotClient is the client API for TgBot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TgBotClient interface {
	TaskAdd(ctx context.Context, in *TaskAddRequest, opts ...grpc.CallOption) (*TaskAddResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type tgBotClient struct {
	cc grpc.ClientConnInterface
}

func NewTgBotClient(cc grpc.ClientConnInterface) TgBotClient {
	return &tgBotClient{cc}
}

func (c *tgBotClient) TaskAdd(ctx context.Context, in *TaskAddRequest, opts ...grpc.CallOption) (*TaskAddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskAddResponse)
	err := c.cc.Invoke(ctx, TgBot_TaskAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tgBotClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, TgBot_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TgBotServer is the server API for TgBot service.
// All implementations must embed UnimplementedTgBotServer
// for forward compatibility.
type TgBotServer interface {
	TaskAdd(context.Context, *TaskAddRequest) (*TaskAddResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedTgBotServer()
}

// UnimplementedTgBotServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTgBotServer struct{}

func (UnimplementedTgBotServer) TaskAdd(context.Context, *TaskAddRequest) (*TaskAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskAdd not implemented")
}
func (UnimplementedTgBotServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedTgBotServer) mustEmbedUnimplementedTgBotServer() {}
func (UnimplementedTgBotServer) testEmbeddedByValue()               {}

// UnsafeTgBotServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TgBotServer will
// result in compilation errors.
type UnsafeTgBotServer interface {
	mustEmbedUnimplementedTgBotServer()
}

func RegisterTgBotServer(s grpc.ServiceRegistrar, srv TgBotServer) {
	// If the following call pancis, it indicates UnimplementedTgBotServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TgBot_ServiceDesc, srv)
}

func _TgBot_TaskAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TgBotServer).TaskAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TgBot_TaskAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TgBotServer).TaskAdd(ctx, req.(*TaskAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TgBot_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TgBotServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TgBot_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TgBotServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TgBot_ServiceDesc is the grpc.ServiceDesc for TgBot service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TgBot_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.TgBot",
	HandlerType: (*TgBotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TaskAdd",
			Handler:    _TgBot_TaskAdd_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _TgBot_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}
